### ISSUE TITLE
Need to reimplement the cache to handle different scenarios bettery

### ISSUE THREAD

**Issue by llayman** [FraunhoferCESE/madcap#180]
The Cache needs a makeover, probably in RxJava and using GreenDAO. 

Consider the following scenarios:

- [ ] Normal operation. Save -> write to memory -> write to db -> upload
- [ ] Shutdown detected. Write memory to db ASAP
- [ ] Logout made. Write to db -> upload
- [ ] Data collection turned off. Write to db.
- [ ] "Upload Now" button. Write to db -> upload immediately
