### ISSUE TITLE
Android Activity Recognition.

### ISSUE THREAD

**Issue by mmueller301** [FraunhoferCESE/madcap#19]
Since last year Android provides an API for activity recognition. We might use it in Madcap.
- [x] research on Android Activity Recognition
- [ ] implement Test App
- [ ] modularize the Test App for reuse
- [ ] integrate Activity recognition into Madcap.
